version: 2.1
orbs:
  node: circleci/node@12.13.0
jobs:
  build-and-run:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm start
workflows:
    build-and-test:
      jobs:
        - build-and-run